# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.5-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "composer.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      # - run: composer install -n --prefer-dist

      # - save_cache:
      #     paths:
      #       - ./vendor
      #     key: v1-dependencies-{{ checksum "composer.json" }}
        
      # # run tests!
      # - run: phpunit
      
      - run:
         name: Download NodeJS v6
         command: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

      #sqlite needed for laravel database
      #nodejs6 needed to run `npm run watch` later
      - run:
         name: Install PHP sqlite and nodejs 6
         command: sudo apt-get install -y libsqlite3-dev nodejs

      - run:
         name: Setup Laravel testing environment variables for CircleCI test
         command: cp .env.testing .env

      # - run:
      #    name: Update composer to latest version
      #    command: composer self-update

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      # - run: composer install -n --prefer-dist
      # - save_cache:
      #     key: composer-v1-{{ checksum "composer.json" }}
      #     paths:
      #       - vendor

      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      # - run:
      #     name: Install NodeJS Packages
      #     command: npm install
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package.json" }}
      #     paths:
      #       - ./node_modules


      ## Cấu hình test
      # - test:
      # override:
      # - ./vendor/bin/phpcs --standard=phpcs.xml app/ -n
      # - ./vendor/bin/phpmd app/ text phpmd.xml
      # - ./vendor/bin/phpunit


      - run:
         name: Run Laravel Server
         command: php artisan serve
         background: true

      # - run:
      #    name: Test 1 - Run Phpunit for Server-Side HTTP Requests & PHP Unit Testing
         # command: vendor/bin/phpunit

      # - run:
      #    name: Test 2 - Run Laravel Desk for Browser Testing
      #    command: php artisan dusk